---
title: Erin Grand's Resume"
author: Erin Grand
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: true
    css: ['css/custom_resume.css', 'css/dd_cv.css', 'resume']
---


```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)
library(glue)

source("cv_printing_functions.r")

googlesheets4::gs4_auth(email = "eringrand@gmail.com", 
                        cache = TRUE, 
                        use_oob = TRUE)

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1x4O3YQoz8cr99gD4v7wLec2e61Pqfim6Qm2J-10AM90",
  sheet_is_publicly_readable = FALSE,
  pdf_mode = params$pdf_mode
)
```

```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```

```{r}
CV$entries_data %<>%
    dplyr::mutate(
    # Build some custom sections by collapsing others
    section = dplyr::case_when(
      section %in% c('data_science_writings', 'by_me_press') ~ 'writings',
      TRUE ~ section
    )
  ) 
```



Aside
================================================================================

<!-- ```{r} -->
<!-- # Build interactive network of positions colored by section -->
<!-- # and connected if they occurred in the same year -->
<!-- datadrivencv::build_network_logo(CV$entries_data) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- if(params$pdf_mode){ -->
<!--   cat("View this resume online with links at _nickstrayer.me/resume/_") -->
<!-- } else { -->
<!--   cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://github.com/nstrayer/cv/raw/master/strayer_resume.pdf)") -->
<!-- } -->
<!-- ``` -->

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV |> print_contact_info()
# CV$contact_info |> 
#  glue_data("- <i class='fa fa-{icon}'></i> {contact}")
```


Language Skills {#skills}
--------------------------------------------------------------------------------

```{r}
CV |> print_skill_bars()
```

Relevant Skills 
--------------------------------------------------------------------------------

```{r}
CV |> print_text_block('skills_aside')
```

Relevant Courses 
--------------------------------------------------------------------------------

```{r}
CV |> print_text_block('courses_aside')
```


Memberships {#other}
--------------------------------------------------------------------------------

#### R-Ladies NYC board member 2020






Main
================================================================================

Erin Grand {#title}
--------------------------------------------------------------------------------

<!-- ```{r} -->
<!-- # Note the special double pipe so we modify the CV object in place -->
<!-- CV <- print_text_block(CV, "intro")  -->
<!-- ``` -->

Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV <- print_section(CV, 'education')
```


Tech Experience {data-icon=suitcase data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV <- print_section(CV, 'industry_positions')
```

<!-- Teaching Experience {data-icon=chalkboard-teacher} -->
<!-- -------------------------------------------------------------------------------- -->


<!-- ```{r} -->
<!-- CV %<>% print_section('teaching_positions') -->
<!-- ``` -->

Research Experience {data-icon=laptop}
--------------------------------------------------------------------------------

```{r}
CV <- print_section(CV, 'research_positions')
```

